### ISSUE TITLE
ansiblemetrics requirements

### ISSUE THREAD

**Issue by arturmartins** [radon-h2020/radon-ansible-metrics#2]
I installed ansible-lint, ansible with ansiblemetrics and I get this warning message:

```
ansiblemetrics 0.3.10 has requirement pyyaml==5.3.1, but you'll have pyyaml 5.4.1 which is incompatible.
```

I wonder if the requirements could be updated?

**Comment by stefanodallapalma** [comment]
Hi @arturmartins,
of course, `ansiblemetrics 0.3.11` (now on PyPI) relies on pyyaml 5.4.1.
