### ISSUE TITLE
Using ansible-metrics over a file ansible structure

### ISSUE THREAD

**Issue by fleetvonr** [radon-h2020/radon-ansible-metrics#4]
As per our email I would like to use the functionality of the ansible-metrics over a file structure containing plays and task files.

In your article, published in The Journal of Systems & Software, it was stated that " Playbook metrics operate within a single playbook; while tasks list metrics can operate either within a playbook (when the construct tasks is present) and within tasks files.", kind of implying to me, that there might me an internal logic that would make it possible to deploy the module over e.g. a complete file structure or a gitlab repository containing playbooks and tasks?

Unfortunately I have not been able to figure something out, except that I would have to write my own logic and loops.
I have only used the module like this:

```python
PLAYBOOK_FOLDER = "yleu/playbooks/"
for playbooks in os.scandir(PLAYBOOK_FOLDER):
    print("-------------------------------------")
    print("Playbook:", playbooks.path)
    data = open(playbooks, "r")
    playbook_data = data.read()
    print("Average play size:", AvgPlaySize(playbook_data).count())
    print("Number of plays:", NumPlays(playbook_data).count())
    print("Number of roles:", NumRoles(playbook_data).count())
    print("Number of ignore_error:", NumIgnoreErrors(playbook_data).count())

TASKS_FOLDER = "yleu/playbooks/roles/common/tasks/"
for taskfile in os.scandir(TASKS_FOLDER):
    print("-------------------------------------")
    print("Task:", taskfile.path)
    data = open(taskfile, "r")
    task_data = data.read()
    print("Number of tasks:", NumTasks(task_data).count())
    print("Number of blocks:", NumBlocks(task_data).count())
```

To my use-case: I have a lot of similarly structured gitlab ansible repositories and I would like to evaluate them with the help of your module.
As far as I know, it would be a python script, run in a docker container, retrieving all repositories of my group and collecting the data.

**Comment by stefanodallapalma** [comment]
Hi @fleetvonr,

Take a look at [this file](https://github.com/radon-h2020/radon-ansible-metrics/blob/master/ansiblemetrics/command_line.py) to have an idea of how to extract those metrics from a root folder. Please note, you can either extract the metrics [individually](https://radon-h2020.github.io/radon-ansible-metrics/quick_start.html#run-specific-metrics) or [all at once](https://radon-h2020.github.io/radon-ansible-metrics/quick_start.html#run-all-metrics).

The general idea is that you load a file (or more) as string and pass that string to the desired metric. For example

```python
from ansiblemetrics.playbook.num_tasks import NumTasks

with open('file/to/playbook.yaml') as f:
    content = f.read()

try:
    print(NumTasks(content).count())
    # Other metrics here
 except TypeError:
    print('Content is not a valid YAML')
```

You can repeat the code above for every Ansible file in you repository. You can use [`os.walk`](https://www.tutorialspoint.com/python/os_walk.htm) to iterate over the files and something like [this code](https://github.com/radon-h2020/radon-repository-miner/blob/c3a75d172e31cfb877e8a0c01467876aeee4a069/repominer/filters.py#L4) to make sure you only load ansible files.

**Comment by fleetvonr** [comment]
Thank you! This helped a lot.
